body_temp/urls.py
from django.urls import path

from .views import (
    BodyTempDayArchiveView,
    BodyTempTodayArchiveView,
    BodyTempCreateView,
    BodyTempUpdateView,
    BodyTempDeleteView,
)

app_name = 'body_temp'

urlpatterns = [
    path('body_temp/<int:pk>/delete',
         BodyTempDeleteView.as_view(),
         name='delete'),
    path('body_temp/<int:pk>/edit/',
         BodyTempUpdateView.as_view(),
         name='edit'),
    path('body_temp/new',
         BodyTempCreateView.as_view(),
         name='new'),
    path('<int:year>/<int:month>/<int:day>',
         BodyTempDayArchiveView.as_view(),
         name='day'),
    path('',
         BodyTempTodayArchiveView.as_view(),
         name='today'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('body_temp.urls')),
]

body_temp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse # 新しく追加


class Staff(models.Model):
    """ スタッフ """
    family_name = models.CharField(
        verbose_name="姓（漢字）",
        max_length=50
    )
    given_name = models.CharField(
        verbose_name='名（漢字）',
        max_length=50
    )
    family_kana = models.CharField(
        verbose_name = '姓（カタカナ）',
        max_length = 50,
    )
    given_kana = models.CharField(
        verbose_name = '名（カタカナ）',
        max_length = 50,
    )  
    department = models.CharField(
        verbose_name="所属部署",
        max_length=225
    )

    def __str__(self):
        return f'{self.family_name} {self.given_name}'

    def name(self):
        """ 氏名 """
        return f'{self.family_name} {self.given_name}'

    class Meta:
        verbose_name = 'スタッフ'
        verbose_name_plural = 'スタッフ'


class BodyTemp(models.Model):
    """ 体温 """
    name = models.ForeignKey(
        Staff,
        verbose_name='名前',
        on_delete=models.PROTECT,
    )
    temp = models.DecimalField(
        verbose_name='体温',
        max_digits=3,
        decimal_places=1,
        blank=True,
        null=True,
    )
    created_at = models.DateField(
        verbose_name='検温日',
        default=timezone.now,
    )
    revised_at = models.DateField(
        verbose_name='更新日',
        auto_now=True,
    )

    def __str__(self):
        return f'{self.created_at} {self.name}'

    class Meta:
        verbose_name = '体温'
        verbose_name_plural = '体温'

    def get_absolute_url(self):
        return reverse('body_temp:day',
                       args=[self.created_at.year, self.created_at.month, self.created_at.day])

body_temp/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from django.urls import reverse_lazy
from .models import BodyTemp


class BodyTempDayArchiveView(DayArchiveView):
    """ 体温測定結果の日毎の一覧表示 """
    model = BodyTemp
    date_field = 'created_at'
    month_format='%m'
    allow_empty = True
    context_object_name = 'body_temp_list'
    template_name = 'body_temp/day.html'

    def get_queryset(self):
        """ 所属部署ごと名前のアイウエオ順に変更 """
        queryset = super().get_queryset()
        queryset = queryset.order_by('name__department', 'name__family_name', 'name__given_name')
        return queryset


class BodyTempTodayArchiveView(TodayArchiveView):
    """ 体温測定結果の日毎の一覧表示 """
    model = BodyTemp
    date_field = 'created_at'
    allow_empty = True
    context_object_name = 'body_temp_list'
    template_name = 'body_temp/day.html'

    def get_queryset(self):
        """ 所属部署ごと名前のアイウエオ順に変更 """
        queryset = super().get_queryset()
        queryset = queryset.order_by('name__department', 'name__family_kana', 'name__given_kana')
        return queryset


class BodyTempCreateView(CreateView):
    """ 体温測定結果の入力 """
    model = BodyTemp
    template_name = 'body_temp/new.html'
    fields = ['name', 'temp','created_at']


class BodyTempUpdateView(UpdateView):
    """ 体温測定結果の変更 """
    model = BodyTemp
    template_name = 'body_temp/edit.html'
    fields = ['name', 'temp', 'created_at']


class BodyTempDeleteView(DeleteView):
    """ 体温測定結果の削除 """
    model = BodyTemp
    context_object_name = 'body_temp'
    template_name = 'body_temp/delete.html'
    success_url = reverse_lazy('body_temp:today')

templates/body_temp/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>{% block title%}{% endblock title %}</title>
</head>
<body>
  {% block content %}{% endblock content %}
</body>
</html>

templates/body_temp/day.html
{% extends 'body_temp/base.html' %}

{% block title%}{{ day|date:"Y年m月d日" }}検温結果一覧{% endblock title%}

{% block content %}

<h1>{{ day|date:"Y年m月d日" }}検温結果一覧</h1>

<p><a href="{% url 'body_temp:new' %}">＋新規追加</a></p>
{% if next_day %}
  <p><a href="{% url 'body_temp:today' %}">＜本日の検温結果へ戻る＞</a></p>
{% endif %}
{% if previous_day %}
  <a href="{% url 'body_temp:day' previous_day.year previous_day.month previous_day.day %}">
    ＜前日
  </a>
{% endif %}
{% if next_day %}
  <a href="{% url 'body_temp:day' next_day.year next_day.month next_day.day %}">
    翌日＞
  </a>
{% endif %}
<br>
<table>
  <thead>
    <tr>
      <th>所属部署</th>
      <th>氏名</th>
      <th>体温</th>
      <th colspan="2">変更・削除</th>
    </tr>
  </thead>
  <tbody>
  {% for body_temp in body_temp_list %}
    <tr>
      <td>{{ body_temp.name.department }}</td>
      <td>{{ body_temp.name }}</td>
      <td>{{ body_temp.temp }}</td>
      <td><a href="{% url 'body_temp:edit' body_temp.pk %}">変更</a></td>
      <td><a href="{% url 'body_temp:delete' body_temp.pk %}">削除</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock content %}

templates/body_temp/delete.html
{% extends 'body_temp/base.html' %}

{% block title %}検温結果削除{% endblock title %}

{% block content %}

<h1>検温結果削除</h1>

<form action="" method="post">
  {% csrf_token %}
  <p>{{ body_temp.created_at}} {{ body_temp.name }} 様の検温結果を削除します。</p>
  <input type="submit" value="削除">
</form>

{% endblock content %}

templates/body_temp/edit.html
<!-- templates/body_temp_edit.html -->
{% extends 'body_temp/base.html' %}

{% block title %}検温結果変更{% endblock title %}

{% block content %}

<h1>検温結果変更</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="変更">
</form>

{% endblock content %}

templates/body_temp/new.html
<!-- templates/body_temp_new.html -->
{% extends 'body_temp/base.html' %}

{% block title %}検温結果入力{% endblock title %}

{% block content %}

<h1>検温結果入力</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="保存">
</form>

{% endblock content %}